AWSTemplateFormatVersion: "2010-09-09"
Description: "🌱🌱🌱 オクラの観察！"

Resources:
  # S3バケット
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${AWS::StackName}-s3-bucket
      VersioningConfiguration:
        Status: Suspended
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - "*"
            MaxAge: 3000
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-s3-bucket"

  # S3バケットを操作するためのIAMユーザ
  S3BucketUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub ${AWS::StackName}-s3-bucket-user
      Path: /
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-s3-bucket-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"

Outputs:
  S3BucketName:
    Description: "S3バケット名。"
    Value: !Ref S3Bucket
  S3BucketDomainName:
    Description: "S3バケットエンドポイント。"
    Value: !GetAtt S3Bucket.DomainName
